// Classes the Compose compiler should treat as stable even though they come from non-Compose modules.
// See https://developer.android.com/develop/ui/compose/performance/stability/fix#configuration-file
ru.finassist.pf.core.**
ru.finassist.pf.feature.*.api.**
kotlinx.collections.immutable.**
